# Generated by Django 5.0 on 2024-02-23 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_employee_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_Picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="employee",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
